name: 'FawltyDeps'
description: 'Check a Python project for _undeclared_ and _unused_ 3rd party dependencies'
  # Inspired by and adapted from:
  # https://github.com/psf/black/blob/main/action.yml
  # https://github.com/isort/isort-action
inputs:
  options:
    description: "Options passed to fawltydeps. Use `fawltydeps --help` to see available options. Default:
      ''"
    required: false
    default: ""
  fawltydeps-version:
    description: Version of fawltydeps to use
    required: false
    default: null
  requirements-files:
    description: >
      path(s) to requirements files that should be installed to properly
      configure third-party imports
    required: false
  paths:
    description: >
      files or directories to scan for dependency issues
    required: false
    default: null
branding:
  color: "purple"
  icon: "check-circle"
outputs:
  fawltydeps-result:
    description: fawltydeps result
    value: ${{ steps.run-fawltydeps.outputs.fawltydeps-output }}
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/bin/ensure_python
      shell: bash
    - run: >
        $GITHUB_ACTION_PATH/bin/install_packages
        ${{ inputs.fawltydeps-version }}
        ${{ inputs.requirements-files || inputs.requirementsFiles }}
      shell: bash
    - id: run-fawltydeps
      run: >
        $GITHUB_ACTION_PATH/bin/run_fawltydeps
        ${{ inputs.options }}
        ${{ inputs.paths }}
      shell: bash
