name: 'FawltyDeps'
description: 'Check a Python project for _undeclared_ and _unused_ 3rd party dependencies'
# Inspired by and adapted from https://github.com/psf/black/blob/main/action.yml
inputs:
  options:
    description: "Options passed to fawltydeps. Use `fawltydeps --help` to see available options. Default:
      ''"
    required: false
    default: ""
  summary:
    description: "Whether to add the output to the workflow summary"
    required: false
    default: true
branding:
  color: "purple"
  icon: "check-circle"
runs:
  using: 'docker'
  image: 'Dockerfile'
  steps:
    - name: fawltydeps
      run: |
        set -euo pipefail
        set +e
        out=$(fawltydeps $INPUT_OPTIONS $INPUT_SRC)
        exit_code=$?
        set -e

        echo "$out"

        if [[ "${{ inputs.summary }}" = "true" ]]; then
          echo 
          echo "\`\`\`python" >> "$GITHUB_STEP_SUMMARY"
          echo "${out}" >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
        fi

        exit "$exit_code"
  env:
      INPUT_OPTIONS: ${{ inputs.options }}
      INPUT_SRC: ${{ inputs.src }}
      pythonioencoding: utf-8
  shell: bash

