on: [push]

jobs:
  fawltydeps:
    runs-on: ubuntu-latest
    name: FawltyDeps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: FawltyDeps
        uses: ./
        id: fawltydeps-selftest
        with:
          args: "--help"

